export const INIT = 'INIT';

export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
export const UPDATE_POPUP = 'UPDATE_POPUP';

export const UPDATE_RUNNING_TIMER_ID = 'UPDATE_RUNNING_TIMER_ID';
export const UPDATE_RUNNING_FLAG = 'UPDATE_RUNNING_FLAG';
export const DECREASE_RUNNING_DURATION = 'DECREASE_RUNNING_DURATION';

export const UPDATE_SELECTING_TIMER_ID = 'UPDATE_SELECTING_TIMER_ID';

export const ADD_TIMER = 'ADD_TIMER';
export const EDIT_TIMER = 'EDIT_TIMER';
export const DELETE_TIMER = 'DELETE_TIMER';
export const MOVE_TIMER_UP = 'MOVE_TIMER_UP';
export const MOVE_TIMER_DOWN = 'MOVE_TIMER_DOWN';

export const RESET_DATA = 'RESET_DATA';
